### ISSUE TITLE
Consider Increasing Upload Limit to 30MB

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TeamFelNull/IamMusicPlayer#61]
I have one song I love but I cannot upload it and I don't see a way to manually set mp3s for my server. Or maybe just allow me to drop mp3s in my server folder >_>

**Comment by crisvuchs** [comment]
Are you getting disconnected from the server with a packet size error when trying to upload it? I was having an issue where I would get kicked from the server due to packet size when trying to create a playlist and was able to resolve it by adding this a [packet fixer mod](https://www.curseforge.com/minecraft/mc-mods/packet-fixer) to increase the packet size limit.

**Comment by P3rf3ctXZer0** [comment]
I don't remember the context this is a legacy issue.
